language:
  python

matrix:
  include:
  - python: '3.5'
  - python: '3.6'

sudo:
  true

git:
  depth: 1

addons:
  apt:
    packages:
      - swig3.0

before_install:
  - sed 's/#.*//; s/python.*//; s/swig//;' Requirements/system-requirements.txt | xargs sudo apt-get install --no-install-recommends -y

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r Requirements/pip-requirements.txt

before_script:
  - chmod +x scripts/snowboy_build.sh
  - ./scripts/snowboy_build.sh

script:
  - python -u src/tests.py
