language:
  python

matrix:
  include:
  - python: '3.5'
  - python: '3.6'

sudo:
  true

git:
  depth: 1

addons:
  apt:
    packages:
      - swig3.0
      - libxml2-dev
      - libatlas-base-dev
      - portaudio19-dev
      - libssl-dev
      - mpg123
      - flac
      - sox
      - lame

before_install:
  - sudo apt-get install --no-install-recommends -y mpd

install:
  - pip install -r Requirements/pip-requirements.txt

before_script:
  - chmod +x scripts/snowboy_build.sh
  - alias swig='swig3.0'
  - ./scripts/snowboy_build.sh

script:
  - python -u src/tests.py
