# Generated by scripts/localization_gen.py

LANG_CODE = {
    'IETF': 'uk-UK',
    'ISO': 'uk',
    'aws': 'ru-RU',
}

YANDEX_EMOTION = {
    'good': 'добра',
    'neutral': 'нейтральна',
    'evil': 'зла',
}

YANDEX_SPEAKER = {
    'jane': 'Джейн',
    'oksana': 'Оксана',
    'alyss': 'Аліса',
    'omazh': 'Омар',
    'zahar': 'Захар',
    'ermil': 'Саня',
}

RHVOICE_SPEAKER = {
    'anna': 'Аня',
    'anatol': 'Анатол',
    'natalia': 'Наталя',
}

AWS_SPEAKER = {
    'Tatyana': 'Тетяна',
    'Maxim': 'Максим',
}

_LNG = {}
