# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install system dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends mpd alsa-utils flac mpg123 \
        libatlas3-base libexpat1 portaudio19-dev
#        locales
#        locale-gen ru_RU.UTF-8
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install https://github.com/Aculeasis/python-webrtc-audio-processing/releases/download/0.1.3/webrtc_audio_processing-0.1.3-cp38-cp38-linux_x86_64.whl
        pip install -r Requirements/pip-requirements.txt
    - name: Prepare snowboy
      run: |
        cp -f bin/_snowboydetect.so.appveyor src/detectors/snowboy/_snowboydetect.so
    - name: Test with unittest
      run: |
        python -u tests.py
